### ISSUE TITLE
How do you use this mod?

### ISSUE THREAD

**Issue by ReaIName** [MasterofGalaxies/smg2-multiplayer#1]

**Comment by galaxymaster2007** [comment]
Download [multiplayer.xml](https://github.com/MasterofGalaxies/smg2-multiplayer/releases/download/v0.5.1/multiplayer.xml), put it on an SD card or USB drive in a directory named 'riivolution', and start [Riivolution](https://rvlution.net/wiki/Riivolution/) on your Wii.
